### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'randaug'

### ISSUE THREAD

**Issue by siryul** [shijxcs/CSA#1]
Executing python train.py --cfg . /config/cifar10/cifar10_imb001.yaml gives an error showing： `TypeError: __init__() got an unexpected keyword argument 'randaug'`, checking the yaml file there is no such configuration. Please tell me how to solve it, thanks :)

**Comment by shijxcs** [comment]
Thank you for pointing out this issue. We have updated the files in  `./datasets` to fix this bug. Note that the `randaug` is used when optimizing BCL loss, and it is not included in the configuration arguments.
