### ISSUE TITLE
AttributeError: 'ResNet_fe' object has no attribute 'module'

### ISSUE THREAD

**Issue by siryul** [shijxcs/CSA#2]
Running python train.py --cfg ./config/cifar10/cifar10_imb01.yaml displays `AttributeError: 'ResNet_fe' object has no attribute 'module'` on python==3.9.18. And the traceback is :

```
Traceback (most recent call last):
  File "xxx/CSA/CSA/train.py", line 798, in <module>
    main()
  File "xxx/CSA/CSA/train.py", line 98, in main
    main_worker(config.gpu, ngpus_per_node, config, logger, model_dir)
  File "xxx/CSA/CSA/train.py", line 338, in main_worker
    train(train_loader, balance_loader, model, classifier1, classifier2, criterion, optimizer,
  File "xxx/CSA/CSA/train.py", line 442, in train
    mask, logit = get_background_mask(model, block, classifier1, input1, target1, config)
  File "xxx/CSA/CSA/train.py", line 571, in get_background_mask
    target_layer = model.module.last_layer
  File "/opt/homebrew/anaconda3/envs/py39-troch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ResNet_fe' object has no attribute 'module'
```

Could you show the `requirements.txt`? Thank you so much.

**Comment by shijxcs** [comment]
The requirements is listed in [requirements.txt](https://github.com/shijxcs/CSA/blob/main/CSA/requirements.txt). You can create the conda environment by
```
conda create -n py39 python=3.9
conda activate py39
conda install pytorch=1.12.0 torchvision=0.13.0 cudatoolkit=11.3 -c pytorch
pip install yacs==0.1.8
```
I can successfully run `python train.py --cfg ./config/cifar10/cifar10_imb01.yaml` in the above environment.

Have you ever edited the source code? For example, if you have not applied `torch.nn.DataParallel` on the `model`, then you may fail to call `model.module`.

**Comment by siryul** [comment]
> The requirements is listed in [requirements.txt](https://github.com/shijxcs/CSA/blob/main/CSA/requirements.txt). You can create the conda environment by
> 
> ```
> conda create -n py39 python=3.9
> conda activate py39
> conda install pytorch=1.12.0 torchvision=0.13.0 cudatoolkit=11.3 -c pytorch
> pip install yacs==0.1.8
> ```
> 
> I can successfully run `python train.py --cfg ./config/cifar10/cifar10_imb01.yaml` in the above environment.
> 
> Have you ever edited the source code? For example, if you have not applied `torch.nn.DataParallel` on the `model`, then you may fail to call `model.module`.

OK，thanks :)
