### ISSUE TITLE
The Question About 'Balance ratio'

### ISSUE THREAD

**Issue by z7d1** [shijxcs/CSA#3]
Hello, thank you for your great work.

What's meaning of the term ‘Balance Ratio’ in the paper's Figure 1.

Is $N_{tail\ classes}/N_{tail\ classes}$?

**Comment by shijxcs** [comment]
Thanks for your attention.

Balance Ratio $\gamma$ can affect the sampling weight. When $\gamma=0$, we sample each data point with an equal probability. When $\gamma=1$, we re-sample the dataset into a class-balanced one. You can refer to https://github.com/shijxcs/CSA/blob/main/CSA/datasets/cifar100.py#L139 for the detailed implementation.

**Comment by z7d1** [comment]
Thanks for your reply!
